import { Fraunces, Barlow } from 'next/font/google';
import './globals.css';

const FontFraunces = Fraunces({
  variable: '--font-geist-sans',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
});

const FontBarlow = Barlow({
  variable: '--font-geist-mono',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${FontFraunces.variable} ${+FontBarlow.variable} antialiased`}>{children}</body>
    </html>
  );
}
